library(quantmod)
library(TTR)
library(PerformanceAnalytics)
library(ggplot2)
library(scales)

options(stringsAsFactors = FALSE)
symbols<-c("^GSPC","^N225","^HSI","^STI","000001.SS")
suppressWarnings(getSymbols(symbols,src = "yahoo",from="2012-01-01"))
df<-merge(GSPC$GSPC.Adjusted,HSI$HSI.Adjusted,N225$N225.Adjusted,STI$STI.Adjusted,`000001.SS`$`000001.SS.Adjusted`)
names(df)<-c("GSPC","HSI","N225","STI","SSE")
head(df)
tail(df)
class(df)
